/*
 * Copyright (C) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type Want from '@ohos.app.ability.Want';
import type ExtensionContext from 'application.ExtensionContext';

export class VpnExtensionContext extends ExtensionContext {
}

export default class VpnExtensionAbility {
  public context!: VpnExtensionContext;

  onCreate(want: Want): void {
    console.info('VpnExtensionAbility onCreate, want:' + want.abilityName);
  }

  onDestroy(): void {
    console.info('VpnExtensionAbility onDestroy');
  }
}
